# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Thad Anderson
tagline:          'percussionst + composer + audio engineer'
description:      'Associate Professor of Music at UCF <a href="https://www.ucf.edu" target="_blank">UCF</a>. Executive Committee member at <a href="https://www.pas.org" target="_blank">PAS</a>.'
url:              https://thadanderson.github.io
baseurl:          /

author:
  name:           'Thad Anderson'
  url:            https://x.com/thadanderson

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
